CREATE TABLE `users` (
  user_id INT NOT NULL UNIQUE AUTO_INCREMENT,
  username VARCHAR (50) NOT NULL UNIQUE,
  name VARCHAR(50) NOT NULL,
  password VARCHAR(255) NOT NULL,
  access_level INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`)
);