// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Notification        string
	NotificationData    string
	NotificationGifUrls string
	NotificationImgUrls string
	NotificationPack    string
}{
	Notification:        "notification",
	NotificationData:    "notification_data",
	NotificationGifUrls: "notification_gif_urls",
	NotificationImgUrls: "notification_img_urls",
	NotificationPack:    "notification_pack",
}
