// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// NotificationPack is an object representing the database table.
type NotificationPack struct {
	ID         int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	NDID       int         `boil:"nd_id" json:"nd_id" toml:"nd_id" yaml:"nd_id"`
	NPID       null.String `boil:"np_id" json:"np_id,omitempty" toml:"np_id" yaml:"np_id,omitempty"`
	NPOrderID  null.String `boil:"np_order_id" json:"np_order_id,omitempty" toml:"np_order_id" yaml:"np_order_id,omitempty"`
	NPFilterID null.String `boil:"np_filter_id" json:"np_filter_id,omitempty" toml:"np_filter_id" yaml:"np_filter_id,omitempty"`
	NPToolID   null.String `boil:"np_tool_id" json:"np_tool_id,omitempty" toml:"np_tool_id" yaml:"np_tool_id,omitempty"`
	NPName     null.String `boil:"np_name" json:"np_name,omitempty" toml:"np_name" yaml:"np_name,omitempty"`
	CreatedAt  time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt  time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *notificationPackR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L notificationPackL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var NotificationPackColumns = struct {
	ID         string
	NDID       string
	NPID       string
	NPOrderID  string
	NPFilterID string
	NPToolID   string
	NPName     string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "id",
	NDID:       "nd_id",
	NPID:       "np_id",
	NPOrderID:  "np_order_id",
	NPFilterID: "np_filter_id",
	NPToolID:   "np_tool_id",
	NPName:     "np_name",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}

var NotificationPackTableColumns = struct {
	ID         string
	NDID       string
	NPID       string
	NPOrderID  string
	NPFilterID string
	NPToolID   string
	NPName     string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "notification_packs.id",
	NDID:       "notification_packs.nd_id",
	NPID:       "notification_packs.np_id",
	NPOrderID:  "notification_packs.np_order_id",
	NPFilterID: "notification_packs.np_filter_id",
	NPToolID:   "notification_packs.np_tool_id",
	NPName:     "notification_packs.np_name",
	CreatedAt:  "notification_packs.created_at",
	UpdatedAt:  "notification_packs.updated_at",
}

// Generated where

var NotificationPackWhere = struct {
	ID         whereHelperint
	NDID       whereHelperint
	NPID       whereHelpernull_String
	NPOrderID  whereHelpernull_String
	NPFilterID whereHelpernull_String
	NPToolID   whereHelpernull_String
	NPName     whereHelpernull_String
	CreatedAt  whereHelpertime_Time
	UpdatedAt  whereHelpertime_Time
}{
	ID:         whereHelperint{field: "`notification_packs`.`id`"},
	NDID:       whereHelperint{field: "`notification_packs`.`nd_id`"},
	NPID:       whereHelpernull_String{field: "`notification_packs`.`np_id`"},
	NPOrderID:  whereHelpernull_String{field: "`notification_packs`.`np_order_id`"},
	NPFilterID: whereHelpernull_String{field: "`notification_packs`.`np_filter_id`"},
	NPToolID:   whereHelpernull_String{field: "`notification_packs`.`np_tool_id`"},
	NPName:     whereHelpernull_String{field: "`notification_packs`.`np_name`"},
	CreatedAt:  whereHelpertime_Time{field: "`notification_packs`.`created_at`"},
	UpdatedAt:  whereHelpertime_Time{field: "`notification_packs`.`updated_at`"},
}

// NotificationPackRels is where relationship names are stored.
var NotificationPackRels = struct {
	ND string
}{
	ND: "ND",
}

// notificationPackR is where relationships are stored.
type notificationPackR struct {
	ND *NotificationDatum `boil:"ND" json:"ND" toml:"ND" yaml:"ND"`
}

// NewStruct creates a new relationship struct
func (*notificationPackR) NewStruct() *notificationPackR {
	return &notificationPackR{}
}

// notificationPackL is where Load methods for each relationship are stored.
type notificationPackL struct{}

var (
	notificationPackAllColumns            = []string{"id", "nd_id", "np_id", "np_order_id", "np_filter_id", "np_tool_id", "np_name", "created_at", "updated_at"}
	notificationPackColumnsWithoutDefault = []string{"nd_id", "np_id", "np_order_id", "np_filter_id", "np_tool_id", "np_name"}
	notificationPackColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	notificationPackPrimaryKeyColumns     = []string{"id"}
	notificationPackGeneratedColumns      = []string{}
)

type (
	// NotificationPackSlice is an alias for a slice of pointers to NotificationPack.
	// This should almost always be used instead of []NotificationPack.
	NotificationPackSlice []*NotificationPack

	notificationPackQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	notificationPackType                 = reflect.TypeOf(&NotificationPack{})
	notificationPackMapping              = queries.MakeStructMapping(notificationPackType)
	notificationPackPrimaryKeyMapping, _ = queries.BindMapping(notificationPackType, notificationPackMapping, notificationPackPrimaryKeyColumns)
	notificationPackInsertCacheMut       sync.RWMutex
	notificationPackInsertCache          = make(map[string]insertCache)
	notificationPackUpdateCacheMut       sync.RWMutex
	notificationPackUpdateCache          = make(map[string]updateCache)
	notificationPackUpsertCacheMut       sync.RWMutex
	notificationPackUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single notificationPack record from the query.
func (q notificationPackQuery) One(ctx context.Context, exec boil.ContextExecutor) (*NotificationPack, error) {
	o := &NotificationPack{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for notification_packs")
	}

	return o, nil
}

// All returns all NotificationPack records from the query.
func (q notificationPackQuery) All(ctx context.Context, exec boil.ContextExecutor) (NotificationPackSlice, error) {
	var o []*NotificationPack

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to NotificationPack slice")
	}

	return o, nil
}

// Count returns the count of all NotificationPack records in the query.
func (q notificationPackQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count notification_packs rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q notificationPackQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if notification_packs exists")
	}

	return count > 0, nil
}

// ND pointed to by the foreign key.
func (o *NotificationPack) ND(mods ...qm.QueryMod) notificationDatumQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.NDID),
	}

	queryMods = append(queryMods, mods...)

	query := NotificationData(queryMods...)
	queries.SetFrom(query.Query, "`notification_data`")

	return query
}

// LoadND allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (notificationPackL) LoadND(ctx context.Context, e boil.ContextExecutor, singular bool, maybeNotificationPack interface{}, mods queries.Applicator) error {
	var slice []*NotificationPack
	var object *NotificationPack

	if singular {
		object = maybeNotificationPack.(*NotificationPack)
	} else {
		slice = *maybeNotificationPack.(*[]*NotificationPack)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &notificationPackR{}
		}
		args = append(args, object.NDID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &notificationPackR{}
			}

			for _, a := range args {
				if a == obj.NDID {
					continue Outer
				}
			}

			args = append(args, obj.NDID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`notification_data`),
		qm.WhereIn(`notification_data.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load NotificationDatum")
	}

	var resultSlice []*NotificationDatum
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice NotificationDatum")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for notification_data")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for notification_data")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ND = foreign
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.NDID == foreign.ID {
				local.R.ND = foreign
				break
			}
		}
	}

	return nil
}

// SetND of the notificationPack to the related item.
// Sets o.R.ND to related.
// Adds o to related.R.NDNotificationPacks.
func (o *NotificationPack) SetND(ctx context.Context, exec boil.ContextExecutor, insert bool, related *NotificationDatum) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `notification_packs` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"nd_id"}),
		strmangle.WhereClause("`", "`", 0, notificationPackPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.NDID = related.ID
	if o.R == nil {
		o.R = &notificationPackR{
			ND: related,
		}
	} else {
		o.R.ND = related
	}

	if related.R == nil {
		related.R = &notificationDatumR{
			NDNotificationPacks: NotificationPackSlice{o},
		}
	} else {
		related.R.NDNotificationPacks = append(related.R.NDNotificationPacks, o)
	}

	return nil
}

// NotificationPacks retrieves all the records using an executor.
func NotificationPacks(mods ...qm.QueryMod) notificationPackQuery {
	mods = append(mods, qm.From("`notification_packs`"))
	return notificationPackQuery{NewQuery(mods...)}
}

// FindNotificationPack retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindNotificationPack(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*NotificationPack, error) {
	notificationPackObj := &NotificationPack{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `notification_packs` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, notificationPackObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from notification_packs")
	}

	return notificationPackObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *NotificationPack) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no notification_packs provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(notificationPackColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	notificationPackInsertCacheMut.RLock()
	cache, cached := notificationPackInsertCache[key]
	notificationPackInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			notificationPackAllColumns,
			notificationPackColumnsWithDefault,
			notificationPackColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(notificationPackType, notificationPackMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(notificationPackType, notificationPackMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `notification_packs` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `notification_packs` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `notification_packs` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, notificationPackPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into notification_packs")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == notificationPackMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for notification_packs")
	}

CacheNoHooks:
	if !cached {
		notificationPackInsertCacheMut.Lock()
		notificationPackInsertCache[key] = cache
		notificationPackInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the NotificationPack.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *NotificationPack) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	notificationPackUpdateCacheMut.RLock()
	cache, cached := notificationPackUpdateCache[key]
	notificationPackUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			notificationPackAllColumns,
			notificationPackPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update notification_packs, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `notification_packs` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, notificationPackPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(notificationPackType, notificationPackMapping, append(wl, notificationPackPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update notification_packs row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for notification_packs")
	}

	if !cached {
		notificationPackUpdateCacheMut.Lock()
		notificationPackUpdateCache[key] = cache
		notificationPackUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q notificationPackQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for notification_packs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for notification_packs")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o NotificationPackSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notificationPackPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `notification_packs` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, notificationPackPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in notificationPack slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all notificationPack")
	}
	return rowsAff, nil
}

var mySQLNotificationPackUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *NotificationPack) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no notification_packs provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(notificationPackColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLNotificationPackUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	notificationPackUpsertCacheMut.RLock()
	cache, cached := notificationPackUpsertCache[key]
	notificationPackUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			notificationPackAllColumns,
			notificationPackColumnsWithDefault,
			notificationPackColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			notificationPackAllColumns,
			notificationPackPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert notification_packs, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`notification_packs`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `notification_packs` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(notificationPackType, notificationPackMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(notificationPackType, notificationPackMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for notification_packs")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == notificationPackMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(notificationPackType, notificationPackMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for notification_packs")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for notification_packs")
	}

CacheNoHooks:
	if !cached {
		notificationPackUpsertCacheMut.Lock()
		notificationPackUpsertCache[key] = cache
		notificationPackUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single NotificationPack record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *NotificationPack) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no NotificationPack provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), notificationPackPrimaryKeyMapping)
	sql := "DELETE FROM `notification_packs` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from notification_packs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for notification_packs")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q notificationPackQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no notificationPackQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from notification_packs")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for notification_packs")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o NotificationPackSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notificationPackPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `notification_packs` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, notificationPackPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from notificationPack slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for notification_packs")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *NotificationPack) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindNotificationPack(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *NotificationPackSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := NotificationPackSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notificationPackPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `notification_packs`.* FROM `notification_packs` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, notificationPackPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in NotificationPackSlice")
	}

	*o = slice

	return nil
}

// NotificationPackExists checks if the NotificationPack row exists.
func NotificationPackExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `notification_packs` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if notification_packs exists")
	}

	return exists, nil
}
