// Code generated by SQLBoiler 4.8.6 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// NotificationGifURL is an object representing the database table.
type NotificationGifURL struct {
	ID        int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	NDID      int         `boil:"nd_id" json:"nd_id" toml:"nd_id" yaml:"nd_id"`
	NguURL    null.String `boil:"ngu_url" json:"ngu_url,omitempty" toml:"ngu_url" yaml:"ngu_url,omitempty"`
	CreatedAt time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *notificationGifURLR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L notificationGifURLL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var NotificationGifURLColumns = struct {
	ID        string
	NDID      string
	NguURL    string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "id",
	NDID:      "nd_id",
	NguURL:    "ngu_url",
	CreatedAt: "created_at",
	UpdatedAt: "updated_at",
}

var NotificationGifURLTableColumns = struct {
	ID        string
	NDID      string
	NguURL    string
	CreatedAt string
	UpdatedAt string
}{
	ID:        "notification_gif_urls.id",
	NDID:      "notification_gif_urls.nd_id",
	NguURL:    "notification_gif_urls.ngu_url",
	CreatedAt: "notification_gif_urls.created_at",
	UpdatedAt: "notification_gif_urls.updated_at",
}

// Generated where

var NotificationGifURLWhere = struct {
	ID        whereHelperint
	NDID      whereHelperint
	NguURL    whereHelpernull_String
	CreatedAt whereHelpertime_Time
	UpdatedAt whereHelpertime_Time
}{
	ID:        whereHelperint{field: "`notification_gif_urls`.`id`"},
	NDID:      whereHelperint{field: "`notification_gif_urls`.`nd_id`"},
	NguURL:    whereHelpernull_String{field: "`notification_gif_urls`.`ngu_url`"},
	CreatedAt: whereHelpertime_Time{field: "`notification_gif_urls`.`created_at`"},
	UpdatedAt: whereHelpertime_Time{field: "`notification_gif_urls`.`updated_at`"},
}

// NotificationGifURLRels is where relationship names are stored.
var NotificationGifURLRels = struct {
	ND string
}{
	ND: "ND",
}

// notificationGifURLR is where relationships are stored.
type notificationGifURLR struct {
	ND *NotificationDatum `boil:"ND" json:"ND" toml:"ND" yaml:"ND"`
}

// NewStruct creates a new relationship struct
func (*notificationGifURLR) NewStruct() *notificationGifURLR {
	return &notificationGifURLR{}
}

// notificationGifURLL is where Load methods for each relationship are stored.
type notificationGifURLL struct{}

var (
	notificationGifURLAllColumns            = []string{"id", "nd_id", "ngu_url", "created_at", "updated_at"}
	notificationGifURLColumnsWithoutDefault = []string{"nd_id", "ngu_url"}
	notificationGifURLColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	notificationGifURLPrimaryKeyColumns     = []string{"id"}
	notificationGifURLGeneratedColumns      = []string{}
)

type (
	// NotificationGifURLSlice is an alias for a slice of pointers to NotificationGifURL.
	// This should almost always be used instead of []NotificationGifURL.
	NotificationGifURLSlice []*NotificationGifURL

	notificationGifURLQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	notificationGifURLType                 = reflect.TypeOf(&NotificationGifURL{})
	notificationGifURLMapping              = queries.MakeStructMapping(notificationGifURLType)
	notificationGifURLPrimaryKeyMapping, _ = queries.BindMapping(notificationGifURLType, notificationGifURLMapping, notificationGifURLPrimaryKeyColumns)
	notificationGifURLInsertCacheMut       sync.RWMutex
	notificationGifURLInsertCache          = make(map[string]insertCache)
	notificationGifURLUpdateCacheMut       sync.RWMutex
	notificationGifURLUpdateCache          = make(map[string]updateCache)
	notificationGifURLUpsertCacheMut       sync.RWMutex
	notificationGifURLUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single notificationGifURL record from the query.
func (q notificationGifURLQuery) One(ctx context.Context, exec boil.ContextExecutor) (*NotificationGifURL, error) {
	o := &NotificationGifURL{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for notification_gif_urls")
	}

	return o, nil
}

// All returns all NotificationGifURL records from the query.
func (q notificationGifURLQuery) All(ctx context.Context, exec boil.ContextExecutor) (NotificationGifURLSlice, error) {
	var o []*NotificationGifURL

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to NotificationGifURL slice")
	}

	return o, nil
}

// Count returns the count of all NotificationGifURL records in the query.
func (q notificationGifURLQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count notification_gif_urls rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q notificationGifURLQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if notification_gif_urls exists")
	}

	return count > 0, nil
}

// ND pointed to by the foreign key.
func (o *NotificationGifURL) ND(mods ...qm.QueryMod) notificationDatumQuery {
	queryMods := []qm.QueryMod{
		qm.Where("`id` = ?", o.NDID),
	}

	queryMods = append(queryMods, mods...)

	query := NotificationData(queryMods...)
	queries.SetFrom(query.Query, "`notification_data`")

	return query
}

// LoadND allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (notificationGifURLL) LoadND(ctx context.Context, e boil.ContextExecutor, singular bool, maybeNotificationGifURL interface{}, mods queries.Applicator) error {
	var slice []*NotificationGifURL
	var object *NotificationGifURL

	if singular {
		object = maybeNotificationGifURL.(*NotificationGifURL)
	} else {
		slice = *maybeNotificationGifURL.(*[]*NotificationGifURL)
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &notificationGifURLR{}
		}
		args = append(args, object.NDID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &notificationGifURLR{}
			}

			for _, a := range args {
				if a == obj.NDID {
					continue Outer
				}
			}

			args = append(args, obj.NDID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`notification_data`),
		qm.WhereIn(`notification_data.id in ?`, args...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load NotificationDatum")
	}

	var resultSlice []*NotificationDatum
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice NotificationDatum")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for notification_data")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for notification_data")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ND = foreign
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.NDID == foreign.ID {
				local.R.ND = foreign
				break
			}
		}
	}

	return nil
}

// SetND of the notificationGifURL to the related item.
// Sets o.R.ND to related.
// Adds o to related.R.NDNotificationGifUrls.
func (o *NotificationGifURL) SetND(ctx context.Context, exec boil.ContextExecutor, insert bool, related *NotificationDatum) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE `notification_gif_urls` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, []string{"nd_id"}),
		strmangle.WhereClause("`", "`", 0, notificationGifURLPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.NDID = related.ID
	if o.R == nil {
		o.R = &notificationGifURLR{
			ND: related,
		}
	} else {
		o.R.ND = related
	}

	if related.R == nil {
		related.R = &notificationDatumR{
			NDNotificationGifUrls: NotificationGifURLSlice{o},
		}
	} else {
		related.R.NDNotificationGifUrls = append(related.R.NDNotificationGifUrls, o)
	}

	return nil
}

// NotificationGifUrls retrieves all the records using an executor.
func NotificationGifUrls(mods ...qm.QueryMod) notificationGifURLQuery {
	mods = append(mods, qm.From("`notification_gif_urls`"))
	return notificationGifURLQuery{NewQuery(mods...)}
}

// FindNotificationGifURL retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindNotificationGifURL(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*NotificationGifURL, error) {
	notificationGifURLObj := &NotificationGifURL{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from `notification_gif_urls` where `id`=?", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, notificationGifURLObj)
	if err != nil {
		if errors.Cause(err) == sql.ErrNoRows {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from notification_gif_urls")
	}

	return notificationGifURLObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *NotificationGifURL) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no notification_gif_urls provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(notificationGifURLColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	notificationGifURLInsertCacheMut.RLock()
	cache, cached := notificationGifURLInsertCache[key]
	notificationGifURLInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			notificationGifURLAllColumns,
			notificationGifURLColumnsWithDefault,
			notificationGifURLColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(notificationGifURLType, notificationGifURLMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(notificationGifURLType, notificationGifURLMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO `notification_gif_urls` (`%s`) %%sVALUES (%s)%%s", strings.Join(wl, "`,`"), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO `notification_gif_urls` () VALUES ()%s%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			cache.retQuery = fmt.Sprintf("SELECT `%s` FROM `notification_gif_urls` WHERE %s", strings.Join(returnColumns, "`,`"), strmangle.WhereClause("`", "`", 0, notificationGifURLPrimaryKeyColumns))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into notification_gif_urls")
	}

	var lastID int64
	var identifierCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == notificationGifURLMapping["id"] {
		goto CacheNoHooks
	}

	identifierCols = []interface{}{
		o.ID,
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, identifierCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, identifierCols...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for notification_gif_urls")
	}

CacheNoHooks:
	if !cached {
		notificationGifURLInsertCacheMut.Lock()
		notificationGifURLInsertCache[key] = cache
		notificationGifURLInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the NotificationGifURL.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *NotificationGifURL) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	notificationGifURLUpdateCacheMut.RLock()
	cache, cached := notificationGifURLUpdateCache[key]
	notificationGifURLUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			notificationGifURLAllColumns,
			notificationGifURLPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update notification_gif_urls, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE `notification_gif_urls` SET %s WHERE %s",
			strmangle.SetParamNames("`", "`", 0, wl),
			strmangle.WhereClause("`", "`", 0, notificationGifURLPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(notificationGifURLType, notificationGifURLMapping, append(wl, notificationGifURLPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update notification_gif_urls row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for notification_gif_urls")
	}

	if !cached {
		notificationGifURLUpdateCacheMut.Lock()
		notificationGifURLUpdateCache[key] = cache
		notificationGifURLUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q notificationGifURLQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for notification_gif_urls")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for notification_gif_urls")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o NotificationGifURLSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notificationGifURLPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE `notification_gif_urls` SET %s WHERE %s",
		strmangle.SetParamNames("`", "`", 0, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, notificationGifURLPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in notificationGifURL slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all notificationGifURL")
	}
	return rowsAff, nil
}

var mySQLNotificationGifURLUniqueColumns = []string{
	"id",
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *NotificationGifURL) Upsert(ctx context.Context, exec boil.ContextExecutor, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no notification_gif_urls provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(notificationGifURLColumnsWithDefault, o)
	nzUniques := queries.NonZeroDefaultSet(mySQLNotificationGifURLUniqueColumns, o)

	if len(nzUniques) == 0 {
		return errors.New("cannot upsert with a table that cannot conflict on a unique column")
	}

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzUniques {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	notificationGifURLUpsertCacheMut.RLock()
	cache, cached := notificationGifURLUpsertCache[key]
	notificationGifURLUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			notificationGifURLAllColumns,
			notificationGifURLColumnsWithDefault,
			notificationGifURLColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			notificationGifURLAllColumns,
			notificationGifURLPrimaryKeyColumns,
		)

		if !updateColumns.IsNone() && len(update) == 0 {
			return errors.New("models: unable to upsert notification_gif_urls, could not build update column list")
		}

		ret = strmangle.SetComplement(ret, nzUniques)
		cache.query = buildUpsertQueryMySQL(dialect, "`notification_gif_urls`", update, insert)
		cache.retQuery = fmt.Sprintf(
			"SELECT %s FROM `notification_gif_urls` WHERE %s",
			strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, ret), ","),
			strmangle.WhereClause("`", "`", 0, nzUniques),
		)

		cache.valueMapping, err = queries.BindMapping(notificationGifURLType, notificationGifURLMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(notificationGifURLType, notificationGifURLMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	result, err := exec.ExecContext(ctx, cache.query, vals...)

	if err != nil {
		return errors.Wrap(err, "models: unable to upsert for notification_gif_urls")
	}

	var lastID int64
	var uniqueMap []uint64
	var nzUniqueCols []interface{}

	if len(cache.retMapping) == 0 {
		goto CacheNoHooks
	}

	lastID, err = result.LastInsertId()
	if err != nil {
		return ErrSyncFail
	}

	o.ID = int(lastID)
	if lastID != 0 && len(cache.retMapping) == 1 && cache.retMapping[0] == notificationGifURLMapping["id"] {
		goto CacheNoHooks
	}

	uniqueMap, err = queries.BindMapping(notificationGifURLType, notificationGifURLMapping, nzUniques)
	if err != nil {
		return errors.Wrap(err, "models: unable to retrieve unique values for notification_gif_urls")
	}
	nzUniqueCols = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), uniqueMap)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.retQuery)
		fmt.Fprintln(writer, nzUniqueCols...)
	}
	err = exec.QueryRowContext(ctx, cache.retQuery, nzUniqueCols...).Scan(returns...)
	if err != nil {
		return errors.Wrap(err, "models: unable to populate default values for notification_gif_urls")
	}

CacheNoHooks:
	if !cached {
		notificationGifURLUpsertCacheMut.Lock()
		notificationGifURLUpsertCache[key] = cache
		notificationGifURLUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single NotificationGifURL record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *NotificationGifURL) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no NotificationGifURL provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), notificationGifURLPrimaryKeyMapping)
	sql := "DELETE FROM `notification_gif_urls` WHERE `id`=?"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from notification_gif_urls")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for notification_gif_urls")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q notificationGifURLQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no notificationGifURLQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from notification_gif_urls")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for notification_gif_urls")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o NotificationGifURLSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notificationGifURLPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM `notification_gif_urls` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, notificationGifURLPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from notificationGifURL slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for notification_gif_urls")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *NotificationGifURL) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindNotificationGifURL(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *NotificationGifURLSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := NotificationGifURLSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), notificationGifURLPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT `notification_gif_urls`.* FROM `notification_gif_urls` WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 0, notificationGifURLPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in NotificationGifURLSlice")
	}

	*o = slice

	return nil
}

// NotificationGifURLExists checks if the NotificationGifURL row exists.
func NotificationGifURLExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from `notification_gif_urls` where `id`=? limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if notification_gif_urls exists")
	}

	return exists, nil
}
